//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_ProyectoDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int CancionID { get; set; }
        public string NombreCancion { get; set; }
        public Nullable<double> Duracion { get; set; }
        public Nullable<short> AnioLanzamiento { get; set; }
        public string Compositor { get; set; }
        public int AlbumID { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
